name: Sync Sub-Branch with Main

on:
  pull_request:
    types: [closed]

jobs:
  sync_branch:
    if: |
      github.event.pull_request.merged == true
      github.event.pull_request.base.ref != 'main'
      (github.event.pull_request.base.ref == 'server-web' || github.event.pull_request.base.ref == 'client-web' || github.event.pull_request.base.ref == 'client-windows')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Clone sub-branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        path: ${{ github.event.pull_request.head.ref }}

    - name: Add, commit, and push changes
      run: |
        git add .
        git commit -m "Sync ${GITHUB_REF#refs/heads/} with main branch"
        git push
