name: Sync Branch with Main into Sub-Folder

on:
  workflow_dispatch:
    inputs:
      branch-name:
        type: choice
        description: 'Name of the branch to sync with main'
        required: true
        options:
          - server-web
          - client-web
          - client-windows

jobs:
  sync_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git identity
        run: |
          git config --global user.email "joe@brownboxstudio.com"
          git config --global user.name "joegutman"

      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Create working directory
        run: |
          branch_name="${{ github.event.inputs.branch-name }}"
          mkdir -p "${branch_name//-/_}"

      - name: Copy files from branch
        run: |
          git checkout ${{ github.event.inputs.branch-name }} -- '*'
        working-directory: ./${branch_name//-/_}

      - name: List copied files
        run: ls -l
