name: Sync Branch with Main into Sub-Folder

on:
  workflow_dispatch:  # This event triggers the workflow manually

jobs:
  sync_branch:
    runs-on: ubuntu-latest

    inputs:
      branch-name:
        description: 'Name of the branch to sync with main'
        required: true

    steps:
      - name: Set up Git identity
        run: |
          git config --global user.email "joe@brownboxstudio.com"
          git config --global user.name "joegutman"

      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Checkout branch to sync
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch-name }}

      - name: Move files to folder
        run: |
          mv ./* ./${{ github.event.inputs.branch-name//[-]/_ }}

      - name: Add, commit, and push changes
        run: |
          git add .
          git commit -m "Sync ${{ github.event.inputs.branch-name }} with main branch"
          git push
